version: '2'
services:
  mediawiki:
    image: 'revianlabs/mediawiki-ve-bundle'
    ports:
      - '8000:80'
    volumes:
      - 'mediawiki_data/images:/var/www/html/images'
      - 'mediawiki_data/LocalSettings.php:/var/www/html/LocalSettings.php'
      - 'parsoid_data:/usr/lib/parsoid'

